FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /app


COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn


RUN chmod +x mvnw


RUN ./mvnw dependency:go-offline -B


COPY src src


RUN ./mvnw clean package -DskipTests


FROM eclipse-temurin:17-jre-alpine

WORKDIR /app


COPY --from=builder /app/target/*.jar app.jar


ENV SPRING_PROFILES_ACTIVE=docker

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]